"""WAF / CDN fingerprinting (a compact, wafw00f-style heuristic).

Inspects response headers, cookies and server strings from a normal request, and
optionally sends a benign "suspicious" request to see whether a protective layer
trips (403/406/429 + a block signature).  Standard-library only.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from urllib.parse import quote

from ..net.http import HttpClient
from .waf_bypass import _BLOCK_SIGNS  # shared block-page body signatures

# name -> list of (where, needle) signatures. where ∈ {header:<h>, cookie, server, body}
_SIGNATURES: dict[str, list[tuple[str, str]]] = {
    "Cloudflare": [("header:cf-ray", ""), ("server", "cloudflare"), ("cookie", "__cf_bm"), ("cookie", "cf_clearance")],
    "Akamai": [("header:x-akamai-transformed", ""), ("cookie", "ak_bmsc"), ("server", "akamaighost")],
    "Imperva/Incapsula": [("header:x-iinfo", ""), ("cookie", "incap_ses"), ("cookie", "visid_incap"), ("header:x-cdn", "incapsula")],
    "AWS WAF / CloudFront": [("header:x-amz-cf-id", ""), ("server", "cloudfront"), ("header:x-amzn-requestid", "")],
    "Sucuri": [("header:x-sucuri-id", ""), ("header:x-sucuri-cache", ""), ("server", "sucuri")],
    "F5 BIG-IP ASM": [("cookie", "ts01"), ("cookie", "bigipserver"), ("header:x-wa-info", "")],
    "Barracuda": [("cookie", "barra_counter_session"), ("cookie", "barracuda_")],
    "Citrix NetScaler": [("cookie", "citrix_ns_id"), ("cookie", "ns_af"), ("header:via", "ns-cache")],
    "Fortinet FortiWeb": [("cookie", "fortiwafsid"), ("header:server", "fortiweb")],
    "Wordfence": [("body", "generated by wordfence"), ("body", "your access to this site has been limited")],
    "ModSecurity": [("server", "mod_security"), ("body", "mod_security"), ("body", "not acceptable")],
    "DDoS-Guard": [("server", "ddos-guard"), ("cookie", "__ddg")],
    "StackPath": [("server", "stackpath"), ("header:x-sp-waf", "")],
    "Reblaze": [("cookie", "rbzid"), ("server", "reblaze")],
    "Fastly": [("header:x-served-by", "cache-"), ("header:fastly-debug-digest", "")],
    "Azure Front Door": [("header:x-azure-ref", ""), ("server", "azure")],
    # Chinese WAFs (signatures cross-checked with wafw00f).
    "SafeDog (安全狗)": [("cookie", "safedog-flow-item"), ("server", "safedog"),
                        ("body", "safedogsite")],
    "Yunsuo (云锁)": [("cookie", "yunsuo_session"), ("body", "yunsuologo")],
    "Jiasule/ChuangYu (加速乐)": [("server", "jiasule-waf"), ("cookie", "__jsluid"),
                                ("cookie", "jsl_tracking"), ("body", "notice-jiasule")],
    "Qihoo 360 (网站宝)": [("server", "qianxin-waf"), ("header:x-powered-by-360wzb", ""),
                         ("body", "wzws-waf-cgi")],
    "Baidu Yunjiasu": [("server", "yunjiasu-nginx")],
    "BaoTa / aaPanel (宝塔)": [("body", "宝塔网站防火墙"), ("body", "waf.bt.cn")],
}

# Benign-but-suspicious payloads (URL-encoded when sent) to see if a WAF trips.
_ATTACK_PAYLOADS = ["<script>alert(1)</script>", "' OR '1'='1", "../../../../etc/passwd"]


@dataclass
class WafResult:
    url: str
    detected: list[str] = field(default_factory=list)
    evidence: dict[str, str] = field(default_factory=dict)
    blocked_probe: bool = False
    block_status: int | None = None
    error: str | None = None


def _match(name: str, sigs: list[tuple[str, str]], headers_lc, cookies, server, body) -> str | None:
    for where, needle in sigs:
        hay = ""
        if where.startswith("header:"):
            hay = headers_lc.get(where.split(":", 1)[1], "")
            if not needle:
                if hay != "":
                    return f"header {where.split(':', 1)[1]} present"
                continue
        elif where == "cookie":
            hay = cookies
        elif where == "server":
            hay = server
        elif where == "body":
            hay = body
        if needle and needle.lower() in hay.lower():
            return f"{where} matches '{needle}'"
    return None


async def detect_waf(client: HttpClient, url: str, *, scope_check=None, active: bool = True) -> WafResult:
    result = WafResult(url=url)
    r = await client.fetch(url, follow_redirects=True, timeout=12.0, scope_check=scope_check)
    if r.status is None:
        result.error = r.error or "unreachable"
        return result

    headers_lc = {k.lower(): v for k, v in r.headers}
    cookies = " ".join(r.get_all("set-cookie")).lower()
    server = " ".join(r.get_all("Server")).lower()
    body = r.text(limit=50_000)

    for name, sigs in _SIGNATURES.items():
        ev = _match(name, sigs, headers_lc, cookies, server, body)
        if ev:
            result.detected.append(name)
            result.evidence[name] = ev

    if active:
        sep = "&" if "?" in url else "?"
        for payload in _ATTACK_PAYLOADS:
            probe_url = f"{url}{sep}moon={quote(payload)}"
            pr = await client.fetch(probe_url, follow_redirects=False,
                                    timeout=10.0, scope_check=scope_check)
            # Many WAFs (Cloudflare challenge, Akamai, custom pages) block with a 200/503
            # body, not a 4xx status — so also match the block page's body signature.
            blocked = pr.status in (403, 406, 429, 501, 503, 999)
            if not blocked and pr.status is not None and pr.body:
                low = pr.text(limit=20_000).lower()
                blocked = any(s in low for s in _BLOCK_SIGNS)
            if blocked:
                result.blocked_probe = True
                result.block_status = pr.status
                # A block that we didn't otherwise fingerprint still signals *a* WAF.
                if not result.detected:
                    result.detected.append("Unknown WAF (request blocked)")
                    result.evidence["Unknown WAF (request blocked)"] = f"probe returned {pr.status}"
                break
    return result
